CUTOFF_DAYS = 2.0
HIGH_RISK_THRESHOLD = -6.0
LOW_RISK_CLIP = -6.001
NEGLIGIBLE_RISK = -30.0
RANDOM_STATE = 42
MODEL_VERSION = "prism-0.1.0"
DISCLAIMER = "Educational research prototype; not for operational decisions."

TREND_COLUMNS = [
    "risk",
    "miss_distance",
    "relative_speed",
    "max_risk_estimate",
    "t_sigma_r",
    "t_sigma_t",
    "t_sigma_n",
    "c_sigma_r",
    "c_sigma_t",
    "c_sigma_n",
    "t_position_covariance_det",
    "c_position_covariance_det",
    "t_obs_used",
    "c_obs_used",
]

SNAPSHOT_COLUMNS = [
    "risk",
    "max_risk_estimate",
    "max_risk_scaling",
    "miss_distance",
    "relative_speed",
    "relative_position_r",
    "relative_position_t",
    "relative_position_n",
    "relative_velocity_r",
    "relative_velocity_t",
    "relative_velocity_n",
    "azimuth",
    "elevation",
    "geocentric_latitude",
    "c_object_type",
    "mission_id",
    "time_to_tca",
    "F10",
    "F3M",
    "AP",
    "SSN",
    "t_sigma_r",
    "t_sigma_t",
    "t_sigma_n",
    "c_sigma_r",
    "c_sigma_t",
    "c_sigma_n",
    "t_sigma_rdot",
    "t_sigma_tdot",
    "t_sigma_ndot",
    "c_sigma_rdot",
    "c_sigma_tdot",
    "c_sigma_ndot",
    "t_position_covariance_det",
    "c_position_covariance_det",
    "t_span",
    "c_span",
    "t_rcs_estimate",
    "c_rcs_estimate",
    "t_ecc",
    "c_ecc",
    "t_j2k_inc",
    "c_j2k_inc",
    "t_j2k_sma",
    "c_j2k_sma",
    "t_h_apo",
    "c_h_apo",
    "t_h_per",
    "c_h_per",
    "t_obs_available",
    "c_obs_available",
    "t_obs_used",
    "c_obs_used",
    "t_actual_od_span",
    "c_actual_od_span",
    "t_recommended_od_span",
    "c_recommended_od_span",
    "t_weighted_rms",
    "c_weighted_rms",
    "t_cd_area_over_mass",
    "c_cd_area_over_mass",
]

FEATURE_DICTIONARY = {
    "risk": "current estimated log collision risk",
    "risk_change": "change in log risk from first to last eligible message",
    "risk_slope": "log-risk trend toward closest approach",
    "risk_delta_last3": "log-risk change across the last three messages",
    "miss_distance": "predicted miss distance at closest approach",
    "relative_speed": "relative speed at closest approach",
    "normalized_separation": "miss distance relative to combined position uncertainty",
    "t_obs_used": "target observations used in orbit determination",
    "c_obs_used": "chaser observations used in orbit determination",
    "t_position_covariance_det": "target position uncertainty volume",
    "c_position_covariance_det": "chaser position uncertainty volume",
    "hours_before_cutoff": "hours between the latest message and the T-48 cutoff",
    "n_messages": "number of eligible conjunction messages",
}
