CUTOFF_DAYS = 2.0
HIGH_RISK_THRESHOLD = -6.0
LOW_RISK_CLIP = -6.001
NEGLIGIBLE_RISK = -30.0
RANDOM_STATE = 42
MODEL_VERSION = "prism-0.1.0"
DISCLAIMER = "Educational research prototype; not for operational decisions."

TREND_COLUMNS = [
    "risk",
    "miss_distance",
    "relative_speed",
    "max_risk_estimate",
    "t_sigma_r",
    "t_sigma_t",
    "t_sigma_n",
    "c_sigma_r",
    "c_sigma_t",
    "c_sigma_n",
    "t_position_covariance_det",
    "c_position_covariance_det",
    "t_obs_used",
    "c_obs_used",
]

SNAPSHOT_COLUMNS = [
    "risk",
    "max_risk_estimate",
    "max_risk_scaling",
    "miss_distance",
    "relative_speed",
    "relative_position_r",
    "relative_position_t",
    "relative_position_n",
    "relative_velocity_r",
    "relative_velocity_t",
    "relative_velocity_n",
    "azimuth",
    "elevation",
    "geocentric_latitude",
    "c_object_type",
    "mission_id",
    "time_to_tca",
    "F10",
    "F3M",
    "AP",
    "SSN",
    "t_sigma_r",
    "t_sigma_t",
    "t_sigma_n",
    "c_sigma_r",
    "c_sigma_t",
    "c_sigma_n",
    "t_sigma_rdot",
    "t_sigma_tdot",
    "t_sigma_ndot",
    "c_sigma_rdot",
    "c_sigma_tdot",
    "c_sigma_ndot",
    "t_position_covariance_det",
    "c_position_covariance_det",
    "t_span",
    "c_span",
    "t_rcs_estimate",
    "c_rcs_estimate",
    "t_ecc",
    "c_ecc",
    "t_j2k_inc",
    "c_j2k_inc",
    "t_j2k_sma",
    "c_j2k_sma",
    "t_h_apo",
    "c_h_apo",
    "t_h_per",
    "c_h_per",
    "t_obs_available",
    "c_obs_available",
    "t_obs_used",
    "c_obs_used",
    "t_actual_od_span",
    "c_actual_od_span",
    "t_recommended_od_span",
    "c_recommended_od_span",
    "t_weighted_rms",
    "c_weighted_rms",
    "t_cd_area_over_mass",
    "c_cd_area_over_mass",
]

FEATURE_DICTIONARY = {
    "risk": "today's reported chance",
    "risk_change": "whether chance rose or fell",
    "risk_slope": "whether chance is climbing",
    "risk_delta_last3": "change across the last three updates",
    "miss_distance": "predicted miss distance",
    "relative_speed": "closing speed",
    "normalized_separation": "miss size versus uncertainty",
    "t_obs_used": "satellite observations used",
    "c_obs_used": "other-object observations used",
    "t_position_covariance_det": "satellite position uncertainty",
    "c_position_covariance_det": "other-object position uncertainty",
    "hours_before_cutoff": "hours left before the 48-hour line",
    "n_messages": "early messages available",
    "max_risk_estimate": "most pessimistic chance in the message",
    "derived_miss_distance": "miss distance from the geometry",
    "t_sigma_r": "satellite radial uncertainty",
    "c_sigma_r": "other-object radial uncertainty",
}

STORY_COPY = {
    "low": {
        "title": "A quiet flyby",
        "blurb": "Wide miss. Copilot and today's number both stay calm.",
    },
    "escalate": {
        "title": "Chance is climbing",
        "blurb": "Early updates get more serious before closest approach.",
    },
    "deescalate": {
        "title": "Early scare, then calmer",
        "blurb": "First alerts looked high; later geometry looks safer.",
    },
    "uncertain": {
        "title": "Needs a human look",
        "blurb": "The guess range crosses the warning line.",
    },
    "failure": {
        "title": "An honest miss",
        "blurb": "A late jump the copilot understated.",
    },
}
